[workspace]
resolver = "2"
members = [
  "crates/risk-core",
  "crates/risk-quickscorer",
  "crates/risk-quickscorer-standalone-l2",
  "crates/risk-server-tokio",
  "crates/tokio-server-batchplane",
  "crates/risk-bench",
  "crates/risk-bench2",
  "crates/risk-bench3",
  "crates/risk-bench-h2",
  "crates/risk-server-glommio",
  "crates/risk-mamba-kernel",
  "crates/risk_mamba_runner",
  "crates/risk-mamba-v1"
]
default-members = [
  "crates/risk-core",
  "crates/risk-quickscorer",
  "crates/risk-quickscorer-standalone-l2",
  "crates/risk-server-tokio",
  "crates/risk-bench",
  "crates/risk-bench2",
  "crates/risk-bench3",
  "crates/risk-server-glommio",
  "crates/risk-mamba-kernel",
  "crates/risk_mamba_runner"
]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
