[workspace]
resolver = "2"
members = [
  "crates/risk-core",
  "crates/risk-quickscorer",
  "crates/risk-quickscorer-standalone-l2",
  "crates/risk-server-tokio",
  "crates/risk-bench3",
  "crates/risk-server-glommio"
]
default-members = [
  "crates/risk-core",
  "crates/risk-quickscorer",
  "crates/risk-quickscorer-standalone-l2",
  "crates/risk-server-tokio",
  "crates/risk-bench3",
  "crates/risk-server-glommio"
]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
